# -*- coding: utf-8 -*-
"""for loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_MqyXSvYov65tjRC9YGYVRn3an60XWF
"""

'''n=int(input())
if n%2!=0:
    print("Weird")
elif n%2==0 &n>2 and n<5:
    print("Not Weird")
elif n%2==0&n>6 and n<20:
    print("Weird")
elif n%2==0 &n>20:
    print("Not Weird")
else:
  print("not")'''

# Example 1: Print the first 10 natural numbers using for loop.
for i in range(1,11):
  print(i)

# Example 2: Python program to print all the even numbers within the given range.
for i in range(10):
 if i%2==0:
  print(i)

# Example 3: Python program to calculate the sum of all numbers from 1 to a given number.
sum = 0
for i in range(1, 11):
 sum += i
print(sum)

# Example 4: Python program to calculate the sum of all the odd numbers within the given range.
sum=0
for i in range(1,10):
  if i%2!=0:
   sum+=i
print (sum)

# Example 5: Python program to print a multiplication table of a given number.
a=int(input())
for i in range(1,11):
  print(a,"x",'i=',a*i)